(function(){
  let mode="locations",editing=null,data={locations:[],regions:[]};
  const categories={city:"Město",settlement:"Osada",ranch:"Ranč",station:"Stanice",harbor:"Přístav",fort:"Pevnost",landmark:"Významné místo"};
  window.renderAtlasManager=async({api,list,escapeHtml,notify})=>{
    data=await api("/api/admin/atlas");
    list.innerHTML=`<div class="atlas-admin-toolbar"><div class="atlas-admin-tabs"><button class="button ${mode==="locations"?"approve":"button-ghost"}" data-atlas-mode="locations">Lokace</button><button class="button ${mode==="regions"?"approve":"button-ghost"}" data-atlas-mode="regions">Regiony</button></div>${!data.locations.length&&!data.regions.length?`<button class="button atlas-seed" type="button">Načíst výchozí atlas</button>`:""}</div><div id="atlas-admin-content"></div>`;
    list.querySelectorAll("[data-atlas-mode]").forEach(button=>button.onclick=()=>{mode=button.dataset.atlasMode;editing=null;window.renderAtlasManager({api,list,escapeHtml,notify})});
    list.querySelector(".atlas-seed")?.addEventListener("click",async()=>{if(!confirm("Vložit všechny výchozí lokace a regiony do Firestore?"))return;try{for(const region of window.DEADSTONE_ATLAS.regions)await api("/api/admin/atlas/regions",{method:"POST",body:JSON.stringify(region)});for(const location of window.DEADSTONE_ATLAS.locations)await api("/api/admin/atlas/locations",{method:"POST",body:JSON.stringify(location)});notify("Výchozí atlas byl uložen do Firestore.");window.renderAtlasManager({api,list,escapeHtml,notify})}catch(error){notify(error.message,true)}});
    mode==="locations"?renderLocations({api,list,escapeHtml,notify}):renderRegions({api,list,escapeHtml,notify});
  };
  function renderLocations(ctx){const {api,list,escapeHtml,notify}=ctx,root=list.querySelector("#atlas-admin-content"),item=editing?data.locations.find(x=>x.id===editing):null;root.innerHTML=`<form id="atlas-location-form" class="content-editor"><h2>${item?"Upravit lokaci":"Nová lokace"}</h2><div class="editor-grid"><label>Název<input id="atlas-name" required maxlength="100" value="${escapeHtml(item?.name||"")}"></label><label>Původní orientační název<input id="atlas-original" maxlength="100" value="${escapeHtml(item?.originalName||"")}"></label><label>Region<select id="atlas-region" required>${regionOptions(item?.region,escapeHtml)}</select></label><label>Typ lokace<input id="atlas-type" required maxlength="80" value="${escapeHtml(item?.type||"")}"></label><label>Kategorie<select id="atlas-category">${Object.entries(categories).map(([key,label])=>`<option value="${key}" ${item?.category===key?"selected":""}>${label}</option>`).join("")}</select></label><label>Pořadí<input id="atlas-order" type="number" value="${item?.order||0}"></label></div><label>Krátký popis<input id="atlas-short" maxlength="300" value="${escapeHtml(item?.shortDescription||"")}"></label><label>Popis<textarea id="atlas-description">${escapeHtml(item?.description||"")}</textarea></label><label>Historie<textarea id="atlas-history">${escapeHtml(item?.history||"")}</textarea></label><label>Významná místa <small>každé na nový řádek</small><textarea id="atlas-places">${escapeHtml((item?.notablePlaces||[]).join("\n"))}</textarea></label><label>URL obrázku<input id="atlas-image" type="url" value="${escapeHtml(item?.imageUrl||"")}"></label><div class="atlas-coordinate-grid"><label>Souřadnice X (%)<input id="atlas-x" type="number" min="0" max="100" step="0.1" value="${item?.mapX??50}"></label><label>Souřadnice Y (%)<input id="atlas-y" type="number" min="0" max="100" step="0.1" value="${item?.mapY??50}"></label></div><p>Kliknutím do mapy nastavíte pozici značky.</p><div class="atlas-admin-map" id="atlas-position-map"><img src="obrazky/atlas-deadstone.png" alt="Editor pozice na mapě"><i class="atlas-admin-pin"></i></div><label><input id="atlas-published" type="checkbox" ${item?.isPublished!==false?"checked":""}> Zobrazit veřejně</label><div class="actions"><button class="button approve">Uložit lokaci</button>${item?`<button class="button button-ghost" type="button" id="atlas-cancel">Zrušit úpravu</button>`:""}</div></form><div class="atlas-admin-items">${data.locations.map(entry=>card(entry,escapeHtml)).join("")||"<p>Ve Firestore zatím nejsou žádné lokace.</p>"}</div>`;
    const x=root.querySelector("#atlas-x"),y=root.querySelector("#atlas-y"),pin=root.querySelector(".atlas-admin-pin"),position=()=>{pin.style.left=`${x.value}%`;pin.style.top=`${y.value}%`};position();[x,y].forEach(input=>input.oninput=position);root.querySelector("#atlas-position-map").onclick=event=>{const box=event.currentTarget.getBoundingClientRect();x.value=((event.clientX-box.left)/box.width*100).toFixed(1);y.value=((event.clientY-box.top)/box.height*100).toFixed(1);position()};
    root.querySelector("#atlas-location-form").onsubmit=async event=>{event.preventDefault();const payload={name:val("atlas-name"),originalName:val("atlas-original"),region:val("atlas-region"),type:val("atlas-type"),category:val("atlas-category"),order:Number(val("atlas-order")),shortDescription:val("atlas-short"),description:val("atlas-description"),history:val("atlas-history"),notablePlaces:val("atlas-places").split("\n").map(v=>v.trim()).filter(Boolean),imageUrl:val("atlas-image"),mapX:Number(x.value),mapY:Number(y.value),isPublished:root.querySelector("#atlas-published").checked};try{await api(item?`/api/admin/atlas/locations/${item.id}`:"/api/admin/atlas/locations",{method:item?"PATCH":"POST",body:JSON.stringify(payload)});editing=null;notify("Lokace byla uložena.");window.renderAtlasManager(ctx)}catch(error){notify(error.message,true)}};bindCards(root,ctx,"locations");root.querySelector("#atlas-cancel")?.addEventListener("click",()=>{editing=null;window.renderAtlasManager(ctx)});
  }
  function renderRegions(ctx){const {api,list,escapeHtml,notify}=ctx,root=list.querySelector("#atlas-admin-content"),item=editing?data.regions.find(x=>x.id===editing):null;root.innerHTML=`<form id="atlas-region-form" class="content-editor"><h2>${item?"Upravit region":"Nový region"}</h2><div class="editor-grid"><label>Název<input id="region-name" required value="${escapeHtml(item?.name||"")}"></label><label>Pořadí<input id="region-order" type="number" value="${item?.order||0}"></label></div><label>Popis<textarea id="region-description">${escapeHtml(item?.description||"")}</textarea></label><label>URL obrázku<input id="region-image" type="url" value="${escapeHtml(item?.imageUrl||"")}"></label><label><input id="region-published" type="checkbox" ${item?.isPublished!==false?"checked":""}> Zobrazit veřejně</label><div class="actions"><button class="button approve">Uložit region</button>${item?`<button class="button button-ghost" type="button" id="atlas-cancel">Zrušit úpravu</button>`:""}</div></form><div class="atlas-admin-items">${data.regions.map(entry=>card(entry,escapeHtml)).join("")||"<p>Ve Firestore zatím nejsou žádné regiony.</p>"}</div>`;root.querySelector("#atlas-region-form").onsubmit=async event=>{event.preventDefault();const payload={name:val("region-name"),description:val("region-description"),imageUrl:val("region-image"),order:Number(val("region-order")),isPublished:root.querySelector("#region-published").checked,focus:item?.focus||{x:50,y:50,zoom:1.7}};try{await api(item?`/api/admin/atlas/regions/${item.id}`:"/api/admin/atlas/regions",{method:item?"PATCH":"POST",body:JSON.stringify(payload)});editing=null;notify("Region byl uložen.");window.renderAtlasManager(ctx)}catch(error){notify(error.message,true)}};bindCards(root,ctx,"regions");root.querySelector("#atlas-cancel")?.addEventListener("click",()=>{editing=null;window.renderAtlasManager(ctx)});
  }
  function card(item,escapeHtml){return `<article class="atlas-admin-item"><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.region||item.description||"")}</p><span class="status-badge ${item.isPublished?"approved":"rejected"}">${item.isPublished?"Veřejné":"Skryté"}</span><div class="actions"><button class="button button-ghost" data-atlas-edit="${item.id}">Upravit</button><button class="button reject" data-atlas-delete="${item.id}">Smazat</button></div></article>`}
  function bindCards(root,ctx,kind){root.querySelectorAll("[data-atlas-edit]").forEach(button=>button.onclick=()=>{editing=button.dataset.atlasEdit;kind==="locations"?renderLocations(ctx):renderRegions(ctx)});root.querySelectorAll("[data-atlas-delete]").forEach(button=>button.onclick=async()=>{if(!confirm("Opravdu tento atlasový záznam smazat?"))return;try{await ctx.api(`/api/admin/atlas/${kind}/${button.dataset.atlasDelete}`,{method:"DELETE"});ctx.notify("Záznam byl smazán.");editing=null;window.renderAtlasManager(ctx)}catch(error){ctx.notify(error.message,true)}})}
  function regionOptions(selected,escapeHtml){return data.regions.map(region=>`<option ${region.name===selected?"selected":""}>${escapeHtml(region.name)}</option>`).join("")||window.DEADSTONE_ATLAS.regions.map(region=>`<option ${region.name===selected?"selected":""}>${escapeHtml(region.name)}</option>`).join("")}
  function val(id){return document.querySelector(`#${id}`).value.trim()}
})();
