window.DEADSTONE_ATLAS = {
  regions: [
    { id:"frostpeak", name:"Frostpeak", slug:"frostpeak", description:"Nehostinný severní kraj tvořený zasněženými vrcholy, ledovými jezery a horskými průsmyky. Oblast je domovem lovců, samotářů a těch, kteří se chtějí skrýt před civilizací.", focus:{x:47,y:18,zoom:1.75}, order:1, isPublished:true },
    { id:"westreach", name:"Westreach", slug:"westreach", description:"Západní kraj hustých lesů, hlubokých údolí a významných obchodních cest. Nachází se zde Deadstone City i horské městečko Pinewood.", focus:{x:37,y:48,zoom:1.7}, order:2, isPublished:true },
    { id:"ironfield", name:"Ironfield", slug:"ironfield", description:"Úrodné srdce státu Deadstone. Rozsáhlé pláně, ranče, železniční spojení a město Red Creek z regionu činí důležité obchodní centrum.", focus:{x:64,y:43,zoom:1.65}, order:3, isPublished:true },
    { id:"southmoor", name:"Southmoor", slug:"southmoor", description:"Jižní kraj plný močálů, plantáží, řek a přístavních cest. Největším městem oblasti je Ashport.", focus:{x:75,y:67,zoom:1.65}, order:4, isPublished:true },
    { id:"red-desert", name:"Red Desert", slug:"red-desert", description:"Pouštní a řídce osídlený kraj, ve kterém přežijí jen ti nejodolnější. Oblast je známá prašnými městy, pevnostmi a dlouhými cestami bez vody.", focus:{x:44,y:78,zoom:1.65}, order:5, isPublished:true },
    { id:"havrani-hreben", name:"Havraní Hřeben", slug:"havrani-hreben", description:"Drsný východní kraj tvořený skalnatými údolími, lesy, doly a pobřežními osadami. Oblast je známá těžbou a nebezpečnými cestami.", focus:{x:87,y:32,zoom:1.7}, order:6, isPublished:true }
  ],
  locations: [
    {id:"deadstone-city",name:"Deadstone City",originalName:"Blackwater",type:"Hlavní město",category:"city",region:"Westreach",mapX:39,mapY:59,shortDescription:"Správní a obchodní centrum státu.",description:"Deadstone City je správním a obchodním centrem celého státu. Sídlí zde vláda, soud, úřady, šerifská kancelář, banka a významní obchodníci.",history:"Město vyrostlo na důležité obchodní stezce a stalo se symbolem nového pořádku.",notablePlaces:["Státní úřad","Banka","Šerifská kancelář"],order:1,isPublished:true},
    {id:"red-creek",name:"Red Creek",originalName:"Valentine",type:"Město",category:"city",region:"Ironfield",mapX:58.8,mapY:42.7,shortDescription:"Největší město v srdci kraje.",description:"Rušné rančerské město a přirozené tržiště úrodného Ironfieldu.",history:"Rozvoj železnice změnil původní osadu v obchodní uzel.",notablePlaces:["Nádraží","Saloon","Dobytčí trh"],order:2,isPublished:true},
    {id:"pinewood",name:"Pinewood",originalName:"Strawberry",type:"Město",category:"city",region:"Westreach",mapX:29.3,mapY:37,shortDescription:"Horské městečko mezi hlubokými lesy.",description:"Klidné horské město živící se dřevem, lovem a obchodem s cestujícími.",history:"Pinewood vznikl u staré lovecké stezky.",notablePlaces:["Lovecký obchod","Pila"],order:3,isPublished:true},
    {id:"oakridge",name:"Oakridge",originalName:"Rhodes",type:"Město",category:"city",region:"Southmoor",mapX:71.4,mapY:63,shortDescription:"Klidné město v jižním kraji.",description:"Město obklopené plantážemi a mokřady, odkud se spravuje vnitrozemí Southmooru.",history:"Bohatství města vyrostlo na půdě a říčním obchodu.",notablePlaces:["Radnice","Plantáže"],order:4,isPublished:true},
    {id:"ashport",name:"Ashport",originalName:"Saint Denis",type:"Přístavní město",category:"harbor",region:"Southmoor",mapX:88.2,mapY:62.3,shortDescription:"Největší přístavní metropole státu.",description:"Brána Deadstone do světa, plná továren, obchodníků a přístavních dělníků.",history:"Přístav z malé osady učinil nejrychleji rostoucí město jihu.",notablePlaces:["Velký přístav","Tržnice","Průmyslová čtvrť"],order:5,isPublished:true},
    {id:"black-harbor",name:"Black Harbor",originalName:"Van Horn",type:"Přístav",category:"harbor",region:"Havraní Hřeben",mapX:90.1,mapY:36.9,shortDescription:"Drsný rybářský přístav.",description:"Ošlehaná pobřežní osada známá rybolovem, pašeráky a námořníky.",history:"Přístav nikdy plně nepodlehl zákonu.",notablePlaces:["Molo","Rybářská krčma"],order:6,isPublished:true},
    {id:"ironhill",name:"Ironhill",originalName:"Annesburg",type:"Město",category:"city",region:"Havraní Hřeben",mapX:91.3,mapY:12.4,shortDescription:"Těžební město pod východními štíty.",description:"Hornické město sevřené mezi horami, lesem a železnicí.",history:"Železná ruda přivedla do kraje dělníky i mocné společnosti.",notablePlaces:["Důl","Železniční depo"],order:7,isPublished:true},
    {id:"dusthaven",name:"Dusthaven",originalName:"Armadillo",type:"Město",category:"city",region:"Red Desert",mapX:44,mapY:79.2,shortDescription:"Největší město pouště.",description:"Prašné město poskytující poslední bezpečí před dlouhou cestou pustinou.",history:"Vzniklo kolem studny a dostavníkové stanice.",notablePlaces:["Studna","Dostavníková stanice"],order:8,isPublished:true},
    {id:"dryfalls",name:"Dryfalls",originalName:"Tumbleweed",type:"Osada",category:"settlement",region:"Red Desert",mapX:31.3,mapY:75.1,shortDescription:"Upadající osada na okraji pouště.",description:"Kdysi rušná osada, kterou obchodní cesty pomalu opustily.",history:"Vítr dnes prohání prach mezi domy lépe než lidé.",notablePlaces:["Starý saloon","Šerifská kancelář"],order:9,isPublished:true},
    {id:"frost-camp",name:"Frost Camp",originalName:"Colter",type:"Osada",category:"settlement",region:"Frostpeak",mapX:38.2,mapY:8.8,shortDescription:"Odlehlá osada v horách.",description:"Tábor v sevření sněhu poskytuje úkryt lovcům a odvážným cestovatelům.",history:"Místo přežívá navzdory zimě a odloučení.",notablePlaces:["Lovecké sruby"],order:10,isPublished:true},
    {id:"cedar-post",name:"Cedar Post",originalName:"Manzanita Post",type:"Poštovní stanice",category:"station",region:"Red Desert",mapX:40.5,mapY:65.2,shortDescription:"Poštovní stanice na hraně pustiny.",description:"Důležitá zastávka pro poštu, dostavníky a zásoby.",history:"Stanice spojuje západní lesy s pouští.",notablePlaces:["Pošta","Stáje"],order:11,isPublished:true},
    {id:"emerald-ranch",name:"Emerald Ranch",originalName:"Emerald Ranch",type:"Ranč",category:"ranch",region:"Ironfield",mapX:74.1,mapY:42.8,shortDescription:"Rozsáhlý obchodní ranč.",description:"Bohatý ranč u železnice dodávající dobytek do celého státu.",history:"Majitelé ranče mají značný vliv na krajský obchod.",notablePlaces:["Stodoly","Ohrady"],order:12,isPublished:true},
    {id:"green-ranch",name:"Green Ranch",originalName:"",type:"Ranč",category:"ranch",region:"Ironfield",mapX:61.2,mapY:49.5,shortDescription:"Rodinný ranč v úrodném kraji.",description:"Úrodné pastviny a blízkost Red Creeku z něj činí vyhledávané hospodářství.",history:"Ranč po generace obdělává stejná rodina.",notablePlaces:["Statek","Pastviny"],order:13,isPublished:true},
    {id:"stone-ranch",name:"Stone Ranch",originalName:"MacFarlane's Ranch",type:"Ranč",category:"ranch",region:"Westreach",mapX:37,mapY:65,shortDescription:"Ranč na západní obchodní cestě.",description:"Soběstačný ranč poskytující práci i odpočinek cestujícím.",history:"Patří mezi nejstarší hospodářství západu.",notablePlaces:["Stáje","Pole"],order:14,isPublished:true},
    {id:"fort-mercer",name:"Fort Mercer",originalName:"Fort Mercer",type:"Pevnost",category:"fort",region:"Red Desert",mapX:37.2,mapY:88,shortDescription:"Pevnost střežící pouštní hranici.",description:"Kamenná pevnost ovládající cesty jižní pustinou.",history:"Pamatuje vojenské výpravy i období opuštění.",notablePlaces:["Hradby","Nádvoří"],order:15,isPublished:true},
    {id:"outlaws-landing",name:"Outlaw's Landing",originalName:"Thieves Landing",type:"Přístav",category:"harbor",region:"Southmoor",mapX:76.3,mapY:80.7,shortDescription:"Útočiště psanců na pobřeží.",description:"Odlehlé kotviště, kde se zákon prosazuje jen velmi obtížně.",history:"Zátoka sloužila pašerákům dávno před vznikem státu.",notablePlaces:["Molo","Skladiště"],order:16,isPublished:true},
    {id:"pine-station",name:"Pine Station",originalName:"Wallace Station",type:"Železniční stanice",category:"station",region:"Westreach",mapX:42.3,mapY:47.3,shortDescription:"Stanice mezi lesy a horami.",description:"Důležitá železniční zastávka pro dřevo, poštu a cestující.",history:"Trať otevřela Westreach rychlejšímu obchodu.",notablePlaces:["Nástupiště","Telegraf"],order:17,isPublished:true},
    {id:"iron-station",name:"Iron Station",originalName:"Riggs Station",type:"Železniční stanice",category:"station",region:"Ironfield",mapX:48.2,mapY:57,shortDescription:"Křižovatka státní železnice.",description:"Stanice propojuje střed státu, západ a jižní kraje.",history:"Okolo kolejí vzniklo malé zázemí železničářů.",notablePlaces:["Depo","Vodárenská věž"],order:18,isPublished:true},
    {id:"wallace-station",name:"Wallace Station",originalName:"",type:"Železniční stanice",category:"station",region:"Westreach",mapX:35,mapY:56.7,shortDescription:"Malá zastávka v západním údolí.",description:"Skromná stanice využívaná rančery, lovci a zásobovacími vlaky.",history:"Jméno nese po prvním přednostovi trati.",notablePlaces:["Nástupiště"],order:19,isPublished:true},
    {id:"marshfield",name:"Marshfield",originalName:"Lagras",type:"Osada",category:"settlement",region:"Southmoor",mapX:65.7,mapY:69.2,shortDescription:"Osada na hraně černých močálů.",description:"Rybářská a lovecká osada přizpůsobená životu mezi vodou a bažinami.",history:"Obyvatelé znají močály lépe než kterákoli mapa.",notablePlaces:["Molo","Rybářské chaty"],order:20,isPublished:true}
  ]
};
