const apiBase=window.DEADSTONE_CONFIG?.apiBase?.replace(/\/$/,"")||location.origin,list=document.querySelector("#my-ticket-list"),detail=document.querySelector("#ticket-detail");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=v=>v?new Date(v._seconds?v._seconds*1000:v).toLocaleString("cs-CZ"):"";
async function api(path,options={}){const r=await fetch(`${apiBase}${path}`,{credentials:"include",headers:{"Content-Type":"application/json"},...options}),b=await r.json();if(!r.ok)throw new Error(b.error||"Chyba požadavku.");return b.data??b}
function state(value){return {waiting:"Čekající",in_progress:"Rozjednaný",closed:"Uzavřený"}[value]||value}
async function openTicket(id){
 const t=await api(`/api/tickets/${id}`);
 detail.innerHTML=`<p class="eyebrow">${esc(t.number)} · ${esc(t.categoryLabel)}</p><h2>${state(t.status)}</h2>${t.assignedName?`<p>Řeší: <strong>${esc(t.assignedName)}</strong></p>`:""}${t.closeReason?`<div class="message">Výsledek: ${esc(t.closeReason)}<br>${esc(t.closingMessage)}</div>`:""}<div class="ticket-thread">${t.messages.map(m=>`<article class="request-card"><strong>${esc(m.authorName)}</strong> <small>${date(m.createdAt)}</small><p>${esc(m.content)}</p>${(m.attachments||[]).map(a=>`<a class="button button-ghost" target="_blank" href="${esc(a.url)}">${esc(a.name)}</a>`).join("")}</article>`).join("")}</div>${t.status!=="closed"?`<form id="reply-form" class="ticket-form"><label>Odpověď<textarea id="reply-content"></textarea></label><label>Odkaz na důkaz nebo soubor <span>Discord, YouTube, Disk, Imgur…</span><input id="reply-link" type="url" placeholder="https://…"></label><button class="button">Odeslat odpověď</button></form>`:""}`;
 document.querySelector("#reply-form")?.addEventListener("submit",async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button");button.disabled=true;try{const link=document.querySelector("#reply-link").value.trim();const content=`${document.querySelector("#reply-content").value}${link?`\n\nPříloha: ${link}`:""}`;await api(`/api/tickets/${id}/messages`,{method:"POST",body:JSON.stringify({content,attachments:[]})});openTicket(id)}catch(error){alert(error.message)}finally{button.disabled=false}});
 history.replaceState(null,"",`?ticket=${id}`);
}
api("/api/tickets/mine").then(items=>{list.innerHTML=items.length?items.map(t=>`<button class="citizen-entry" data-id="${t.id}"><strong>${esc(t.number)}</strong><br>${esc(t.categoryLabel)} · ${state(t.status)}</button>`).join(""):"<p>Zatím nemáš žádný ticket.</p>";list.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openTicket(b.dataset.id));const selected=new URLSearchParams(location.search).get("ticket");if(selected)openTicket(selected)}).catch(()=>location.href=`${apiBase}/api/auth/discord`);
