const apiBase=window.DEADSTONE_CONFIG?.apiBase?.replace(/\/$/,"")||location.origin,list=document.querySelector("#my-ticket-list"),detail=document.querySelector("#ticket-detail");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=v=>v?new Date(v._seconds?v._seconds*1000:v).toLocaleString("cs-CZ"):"";
async function api(path,options={}){const r=await fetch(`${apiBase}${path}`,{credentials:"include",headers:{"Content-Type":"application/json"},...options}),b=await r.json();if(!r.ok)throw new Error(b.error||"Chyba požadavku.");return b.data??b}
async function filesData(files){const selected=[...files];if(selected.length>5)throw new Error("Lze přiložit nejvýše 5 souborů.");if(selected.some(file=>file.size>8*1024*1024))throw new Error("Jeden soubor může mít nejvýše 8 MB.");return Promise.all(selected.map(async file=>{const prepared=await api("/api/tickets/upload",{method:"POST",body:JSON.stringify({name:file.name,mime:file.type,size:file.size})});const upload=await fetch(prepared.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type},body:file});if(!upload.ok)throw new Error(`Přílohu ${file.name} se nepodařilo nahrát.`);return prepared.attachment}))}
function state(value){return {waiting:"Čekající",in_progress:"Rozjednaný",closed:"Uzavřený"}[value]||value}
async function openTicket(id){
 const t=await api(`/api/tickets/${id}`);
 detail.innerHTML=`<p class="eyebrow">${esc(t.number)} · ${esc(t.categoryLabel)}</p><h2>${state(t.status)}</h2>${t.assignedName?`<p>Řeší: <strong>${esc(t.assignedName)}</strong></p>`:""}${t.closeReason?`<div class="message">Výsledek: ${esc(t.closeReason)}<br>${esc(t.closingMessage)}</div>`:""}<div class="ticket-thread">${t.messages.map(m=>`<article class="request-card"><strong>${esc(m.authorName)}</strong> <small>${date(m.createdAt)}</small><p>${esc(m.content)}</p>${(m.attachments||[]).map(a=>`<a class="button button-ghost" target="_blank" href="${esc(a.url)}">${esc(a.name)}</a>`).join("")}</article>`).join("")}</div>${t.status!=="closed"?`<form id="reply-form" class="ticket-form"><label>Odpověď<textarea id="reply-content"></textarea></label><label>Přílohy<input id="reply-files" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.txt"></label><button class="button">Odeslat odpověď</button></form>`:""}`;
 document.querySelector("#reply-form")?.addEventListener("submit",async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button");button.disabled=true;try{await api(`/api/tickets/${id}/messages`,{method:"POST",body:JSON.stringify({content:document.querySelector("#reply-content").value,attachments:await filesData(document.querySelector("#reply-files").files)})});openTicket(id)}catch(error){alert(error.message)}finally{button.disabled=false}});
 history.replaceState(null,"",`?ticket=${id}`);
}
api("/api/tickets/mine").then(items=>{list.innerHTML=items.length?items.map(t=>`<button class="citizen-entry" data-id="${t.id}"><strong>${esc(t.number)}</strong><br>${esc(t.categoryLabel)} · ${state(t.status)}</button>`).join(""):"<p>Zatím nemáš žádný ticket.</p>";list.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openTicket(b.dataset.id));const selected=new URLSearchParams(location.search).get("ticket");if(selected)openTicket(selected)}).catch(()=>location.href=`${apiBase}/api/auth/discord`);
